version: '2'
services:
  react-project:
    build:
      context: .
      dockerfile: Dockerfile
    command: node_modules/.bin/nodemon --exec npm start
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    volumes:
      - .:/home/app/react-project/my-app
      - /home/app/react-project/my-app/node_modules